# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a48ee5af3cd71d1dda9f2746dac46c87cfab36e15f1e48d65b2b1bdef35a7f2db1b2e5eb45322f973bdb04d0d64842f91a379938fe6064aa40c19defab8b8c6e

test:
  secret_key_base: fa3685d6439589ba39d04c36c0ee6d68b5c6c9bf42f566633b8fcfd97f62f79eb3dc99b86329bf3f6a010c08b7d4080221497e28d2d59cb850b183abeb9fdbe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
